import { Button } from '@/components/ui/button'
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty'
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from '@/components/ui/input-otp'
import { Spinner } from '@/components/ui/spinner'
import { useAuth } from '@/contexts/auth-context'
import { createFileRoute } from '@tanstack/react-router'
import { REGEXP_ONLY_DIGITS } from 'input-otp'
import { KeyRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import {toast} from "sonner"

export const Route = createFileRoute('/auth/login/2fa')({
  component: RouteComponent,
})

function RouteComponent() {
  const { loginOTP, isLoading, error } = useAuth();

  const [totpCode, setTotpCode] = useState("");

  const handleLogin = async () => {
    await loginOTP(totpCode);
  }

  useEffect(() => {
    if(error) toast.error(error)
  }, [error])

  return (
    <Empty className='flex flex-col gap-5'>
      <EmptyHeader>
        <EmptyMedia variant={"icon"}><KeyRound /></EmptyMedia>
        <EmptyTitle>Two-factor Authentication</EmptyTitle>
        <EmptyDescription>Please input the two-factor code generated by your authenticator app.</EmptyDescription>
      </EmptyHeader>
      <EmptyContent>
        <InputOTP maxLength={6} pattern={REGEXP_ONLY_DIGITS} className='mx-auto' value={totpCode} onChange={(e) => {setTotpCode(e)}}>
          <InputOTPGroup>
            <InputOTPSlot index={0} />
            <InputOTPSlot index={1} />
            <InputOTPSlot index={2} />
          </InputOTPGroup>
          <InputOTPSeparator />
          <InputOTPGroup>
            <InputOTPSlot index={3} />
            <InputOTPSlot index={4} />
            <InputOTPSlot index={5} />
          </InputOTPGroup>
        </InputOTP>
        <Button disabled={isLoading} onClick={handleLogin}>{isLoading ? <Spinner /> : "Login"}</Button>
      </EmptyContent>
    </Empty>
  )
}
