"use client"

import { useAuth } from "@/components/context/AuthContext"
import { Button } from "@/components/ui/button"
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"
import { InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator } from "@/components/ui/input-otp"
import { Spinner } from "@/components/ui/spinner"
import { REGEXP_ONLY_DIGITS } from "input-otp"
import { KeyRound } from "lucide-react"
import { useState } from "react"
import { toast } from "sonner";

export default function TOTPVerificationPage() {

    const { loginTOTP } = useAuth();

    const [otpCode, setOtpCode] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState("");

    const handleVerify = async (code: string) => {
        setIsLoading(true);
        const response = await loginTOTP(code);
        if(!response.success){
            setError(response.message);
            toast.error(response.message);
            setOtpCode("");
        }

        setIsLoading(false);
    }

    const handleChange = (value: string) => {
        setOtpCode(value);
        setError("");
        if(value.length == 6) handleVerify(value);
    }

    return (
        <div className="min-h-screen w-full flex flex-col gap-5 items-center justify-center">

            <Empty>
                <EmptyHeader>
                    <EmptyMedia variant={"icon"}><KeyRound /></EmptyMedia>
                    <EmptyTitle>Two-factor Authentication</EmptyTitle>
                    <EmptyDescription>Please input the two-factor code generated by your authenticator app.</EmptyDescription>
                </EmptyHeader>
                <EmptyContent>
                    <InputOTP maxLength={6} value={otpCode} onChange={handleChange} disabled={isLoading} pattern={REGEXP_ONLY_DIGITS}>
                        <InputOTPGroup>
                            <InputOTPSlot index={0} aria-invalid={error != ""}/>
                            <InputOTPSlot index={1} aria-invalid={error != ""}/>
                            <InputOTPSlot index={2} aria-invalid={error != ""}/>
                        </InputOTPGroup>
                        <InputOTPSeparator />
                        <InputOTPGroup>
                            <InputOTPSlot index={3} aria-invalid={error != ""}/>
                            <InputOTPSlot index={4} aria-invalid={error != ""}/>
                            <InputOTPSlot index={5} aria-invalid={error != ""}/>
                        </InputOTPGroup>
                    </InputOTP>
                    <Button onClick={() => {handleVerify(otpCode)}} disabled={isLoading}>{isLoading ? <Spinner/> : "Login"}</Button>
                </EmptyContent>
            </Empty>
        </div>
    )
}