/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNodesRouteImport } from './routes/dashboard.nodes'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardLocationsIndexRouteImport } from './routes/dashboard.locations.index'
import { Route as DashboardLocationsLocationIdRouteImport } from './routes/dashboard.locations.$locationId'
import { Route as AuthLogin2faRouteImport } from './routes/auth.login.2fa'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNodesRoute = DashboardNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardLocationsIndexRoute = DashboardLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocationsLocationIdRoute =
  DashboardLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthLogin2faRoute = AuthLogin2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/nodes': typeof DashboardNodesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/login/2fa': typeof AuthLogin2faRoute
  '/dashboard/locations/$locationId': typeof DashboardLocationsLocationIdRoute
  '/dashboard/locations/': typeof DashboardLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/nodes': typeof DashboardNodesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/login/2fa': typeof AuthLogin2faRoute
  '/dashboard/locations/$locationId': typeof DashboardLocationsLocationIdRoute
  '/dashboard/locations': typeof DashboardLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/nodes': typeof DashboardNodesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/login/2fa': typeof AuthLogin2faRoute
  '/dashboard/locations/$locationId': typeof DashboardLocationsLocationIdRoute
  '/dashboard/locations/': typeof DashboardLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/nodes'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/auth/login/2fa'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/nodes'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard'
    | '/auth/login/2fa'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/nodes'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/auth/login/2fa'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nodes': {
      id: '/dashboard/nodes'
      path: '/nodes'
      fullPath: '/dashboard/nodes'
      preLoaderRoute: typeof DashboardNodesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/locations/': {
      id: '/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof DashboardLocationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/locations/$locationId': {
      id: '/dashboard/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/dashboard/locations/$locationId'
      preLoaderRoute: typeof DashboardLocationsLocationIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/login/2fa': {
      id: '/auth/login/2fa'
      path: '/2fa'
      fullPath: '/auth/login/2fa'
      preLoaderRoute: typeof AuthLogin2faRouteImport
      parentRoute: typeof AuthLoginRoute
    }
  }
}

interface AuthLoginRouteChildren {
  AuthLogin2faRoute: typeof AuthLogin2faRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLogin2faRoute: AuthLogin2faRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRouteWithChildren,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardNodesRoute: typeof DashboardNodesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLocationsLocationIdRoute: typeof DashboardLocationsLocationIdRoute
  DashboardLocationsIndexRoute: typeof DashboardLocationsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNodesRoute: DashboardNodesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLocationsLocationIdRoute: DashboardLocationsLocationIdRoute,
  DashboardLocationsIndexRoute: DashboardLocationsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
